# This is a generated file. Not intended for manual editing.
services:
  basket.api:
    build:
      context: "C:\\Users\\nahue\\Desktop\\EShopMicroservices\\src"
      dockerfile: "Services/Basket/Basket.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Basket.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basketapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\nahue\\Desktop\\EShopMicroservices\\src\\Services\\Basket\\Basket.API:/app:rw"
    - "C:\\Users\\nahue\\Desktop\\EShopMicroservices\\src:/src:rw"
    - "C:\\Users\\nahue\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  catalog.api:
    build:
      context: "C:\\Users\\nahue\\Desktop\\EShopMicroservices\\src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\nahue\\Desktop\\EShopMicroservices\\src\\Services\\Catalog\\Catalog.API:/app:rw"
    - "C:\\Users\\nahue\\Desktop\\EShopMicroservices\\src:/src:rw"
    - "C:\\Users\\nahue\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  discount.grpc:
    build:
      context: "C:\\Users\\nahue\\Desktop\\EShopMicroservices\\src"
      dockerfile: "Services/Discount/Discount.gRPC/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Discount.gRPC.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "discountgrpc:dev"
    ports: []
    volumes:
    - "C:\\Users\\nahue\\Desktop\\EShopMicroservices\\src\\Services\\Discount\\Discount.gRPC:/app:rw"
    - "C:\\Users\\nahue\\Desktop\\EShopMicroservices\\src:/src:rw"
    - "C:\\Users\\nahue\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
